---
  - name: Install and configure httpd
    hosts : nodes
    become: yes
    tasks:
        - name: Install httpd
          yum :
           name:
             - httpd
           state: latest

        - name: Start service httpd, if not started
          service:
           name: httpd
           state: started

        - name: service info
          shell:
           cmd: systemctl status httpd
