---
  - name: Install and configure httpd
    hosts : nodes
    become: yes
    tasks:
        - name: Install httpd
          yum :
           name:
             - httpd
           state: latest

        - name: Start service httpd, if not started
          service:
           name: httpd
           state: started
           enabled: yes
           
        - name: Enable and Start service firewalld, if not started
          service:
           name: firewalld
           state: started
           enabled: yes
          
        - name: open firewall ports
          firewalld: 
           service: http
           permanent: yes
           state: enabled
           immediate: yes
        
        - name: install one more software
          yum :
           name: 
           - nginx
           state: latest
         
        - name: copy html content
          copy:
           content: "welcome to the venkys web"
           dest: /var/www/html/index.html 
           
   
        - name: service info
          shell:
           cmd: systemctl status httpd
           
  - name: Check that you can connect (GET) to a page and it returns a status 200
    hosts: localhost
    become: no
    tasks:
    - name: conntect to the webserver
      uri:
       url: http://node1
       status_code: 200
       return_content: yes
      

      
